microsoft/Windows-driver-samples

- README.md
For better privacy, let's use HTTPS for go.microsoft.com links.
> Use HTTPS links in README.md

- filesys/miniFilter/avscan/filter/avscan.c
- filesys/miniFilter/change/change.c
"implmentation" -> implementation
> minor typo fix

- pos/drivers/barcodescanner/PosEvents.cpp
This change fixes a slight issue with the sample barcode scanner driver where some fields in the event struct are left uninitialized so that the event ends up getting rejected by the Barcode Scanner API layer.
> Fix barcode event by fully initializing event header.

- setup/devcon/dump.cpp
I've noticed the recent activity in this repository and was wondering if you would accept some pull requests for better MinGW support.  Here is the first one.  My commit message explains it pretty well.  Thanks!
> devcon: Made DumpDeviceDriversCallback be __stdcall.

- pos/drivers/MagneticStripeReader/Ioctl.cpp
- pos/drivers/barcodescanner/Ioctl.cpp
Reset memory so later memory comparison can succeed.
> ZeroMemory statistics data for retrieval

- audio/sysvad/EndpointsCommon/micarraywavtable.h
- audio/sysvad/ToneGenerator.cpp
Added 32 bit format on Microphone Array 1 & 2 endpoints
> Added 32 bit format on Microphone Array 1 & 2 endpoints.

- avstream/avshws/README.md
@NabilFates here are some revs per customer feedback at https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/5b1a154d-45e4-430b-a5aa-1363484f4008/avshws-sample-documentation-and-other-issues?forum=wdk
> updates per customer feedback

- filesys/miniFilter/cdo/README.md
- sensors/ADXL345Acc/readme.md
- sensors/Activity/readme.md
- sensors/CustomSensors/readme.md
- sensors/Fusion/readme.md
- sensors/Pedometer/readme.md
- sensors/SensorsComboDriver/readme.md
- sensors/SimpleDeviceOrientationSensor/readme.md
Added metadata in sensor sample's recently added README.md files. Added missing FWLINK in filesys cdo minifilter sample README.md.
> Updates to README.md metadata.

- general/toaster/toastDrv/README.md
- general/umdfSkeleton/README.md
- serial/VirtualSerial/README.md
- usb/wdf_osrfx2_lab/README.md
Fixed UMDF platform naming in README.md metadata.
> Update README.md platform metadata.

- network/wlan/WDI/COMMON/HashTable.c
- network/wlan/WDI/COMMON/QosGen.c
- network/wlan/WDI/HEADER/HashTable.h
RtRemvoeKeyFromVaHashTable -> RtRemoveKeyFromVaHashtable
> Typo fixed : RtRemvoeKeyFromVaHashTable -> RtRemoveKeyFromVaHashtable

- filesys/fastfat/close.c
Just reading through the fastfat sample and figured I'd nitpick a bit while I was there.
> Fix some comment typos

- print/XPSDrvSmpl/README.md
#324 
Replace all msdn links with docs links
> Fix outlink URL

- general/ioctl/kmdf/exe/testapp.c
- general/ioctl/wdm/exe/testapp.c
METHOD_NIETHER -> METHOD_NEITHER
> [general/ioctl/exe/testapp.c] Fix typo in comment

- network/trans/WFPSampler/sys/WFPSamplerCalloutDriver.InX
update the tags to properly match
> BUG: Update Tags to match

- general/DCHU/osrfx2_DCHU_base/osrfx2_DCHU_base/driver.c
- general/WinHEC 2017 Lab/Toaster Driver/toaster/toaster.c
- general/toaster/toastDrv/kmdf/bus/dynamic/busenum.c
- general/toaster/toastDrv/kmdf/bus/static/busenum.c
- general/toaster/toastDrv/kmdf/filter/generic/filter.c
- general/toaster/toastDrv/kmdf/func/featured/toaster.c
- general/toaster/toastDrv/kmdf/func/simple/toaster.c
- general/toaster/toastDrv/kmdf/toastmon/toastmon.c
- general/toaster/umdf2/filter/generic/filter.c
- general/toaster/umdf2/func/featured/toaster.c
- general/toaster/umdf2/func/simple/toaster.c
- input/kbfiltr/sys/kbfiltr.c
- input/moufiltr/moufiltr.c
- pofx/UMDF2/Driver/SingleComp/driver.c
- pofx/WDF/Driver/SingleComp/driver.c
- usb/kmdf_enumswitches/sys/driver.c
- usb/kmdf_fx2/driver/driver.c
- usb/umdf2_fx2/driver/driver.c
- usb/umdf_filter_kmdf/kmdf_driver/driver.c
- usb/usbsamp/sys/driver.c
Fixes comments for the DriverEntry Function.
> Fix Comments for DriverEntry function

- .gitmodules
- avstream/sampledevicemft/multipinmft.vcxproj
- avstream/sampledevicemft/multipinmft.vcxproj.Filters
- avstream/sampledevicemft/packages.config
Deleted link with wil nuget package, switched to git submodule instead.
@saredd 
@JoelCorley
> Changed wil nuget package linking to git submodule

- sensors/ADXL345Acc/ADXL345Acc.vcxproj
- sensors/Activity/Activity.vcxproj
- sensors/CustomSensors/CustomSensors.vcxproj
- sensors/Fusion/FusionSensor.vcxproj
- sensors/Pedometer/Pedometer.vcxproj
- sensors/SensorsComboDriver/SensorsComboDriver.vcxproj
- sensors/SimpleDeviceOrientationSensor/SimpleDeviceOrientationSensor.vcxproj
I looked at the commits of all the other projects that added sha256 to the driver sign and did a find and replace.
Can I get a sanity check to see if these changes look right?
> Update sensors drivers

- tools/sdv/samples/SDV-FailDriver-KMDF/driver/fail_driver1.vcxproj
- tools/sdv/samples/SDV-FailDriver-KMDF/driver/fail_driver1.vcxproj.Filters
- tools/sdv/samples/SDV-FailDriver-KMDF/library/fail_library1.vcxproj
- tools/sdv/samples/SDV-FailDriver-KMDF/library/fail_library1.vcxproj.Filters
- tools/sdv/samples/SDV-FailDriver-NDIS/driver/sdvmp.vcxproj
- tools/sdv/samples/SDV-FailDriver-NDIS/driver/sdvmp.vcxproj.Filters
- tools/sdv/samples/SDV-FailDriver-STORPORT/driver/lsi_u3.vcxproj
- tools/sdv/samples/SDV-FailDriver-STORPORT/driver/lsi_u3.vcxproj.Filters
- tools/sdv/samples/SDV-FailDriver-WDM/driver/fail_driver1.vcxproj
- tools/sdv/samples/SDV-FailDriver-WDM/driver/fail_driver1.vcxproj.Filters
Updates the SDV sample drivers to use SHA-256 signing per new policy.
> Update SDV sample drivers to use SHA-256 signing.

- audio/tests/HLK/ThirdPartyApoTests/APODeviceTest.cpp
- audio/tests/HLK/ThirdPartyApoTests/APODeviceTest.h
- audio/tests/HLK/ThirdPartyApoTests/APOOSUpgradeTest.cpp
- audio/tests/HLK/ThirdPartyApoTests/APOOSUpgradeTest.h
- audio/tests/HLK/ThirdPartyApoTests/APOStressTest.cpp
- audio/tests/HLK/ThirdPartyApoTests/APOStressTest.h
- audio/tests/HLK/ThirdPartyApoTests/CAPXHelper.cpp
- audio/tests/HLK/ThirdPartyApoTests/CAPXHelper.h
- audio/tests/HLK/ThirdPartyApoTests/CAPXLoggingFrameworkTests.cpp
- audio/tests/HLK/ThirdPartyApoTests/CAPXLoggingFrameworkTests.h
- audio/tests/HLK/ThirdPartyApoTests/CAPXNotificationFrameworkTests.cpp
- audio/tests/HLK/ThirdPartyApoTests/CAPXNotificationFrameworkTests.h
- audio/tests/HLK/ThirdPartyApoTests/CAPXThreadingFrameworkTests.cpp
- audio/tests/HLK/ThirdPartyApoTests/CAPXThreadingFrameworkTests.h
- audio/tests/HLK/ThirdPartyApoTests/FormatHelpers.h
- audio/tests/HLK/ThirdPartyApoTests/TestEffectsList.cpp
- audio/tests/HLK/ThirdPartyApoTests/TestMediaType.cpp
- audio/tests/HLK/ThirdPartyApoTests/TestMediaType.h
- audio/tests/HLK/ThirdPartyApoTests/TestWasapiUseFromAudioDg.cpp
- audio/tests/HLK/ThirdPartyApoTests/Wrappers.h
- audio/tests/HLK/ThirdPartyApoTests/audioconnectionutil.h
- audio/tests/HLK/ThirdPartyApoTests/sinewave.h
- audio/tests/HLK/ThirdPartyApoTests/stdafx.h
This change is to add the HLK APO tests to the windows-driver-samples to allow for any partners to take a look at the tests to know what exactly is being tested when they run the HLK APO tests.
> Adds the HLK APO tests to the public github for windows-driver-samples.

- hid/vhidmini2/inc/common.h
The same define is also found 4 lines below.
> Remove duplicate VHIDMINI_DEVICE_STRING define

- filesys/cdfs/cdfs.vcxproj
- filesys/fastfat/fastfat.vcxproj
update hash algorithm to sha256 for cdfs and fastfat WDK samples.
> update hash algorithm to sha256

- serial/VirtualSerial2/ComPort/VirtualSerial2um.vcxproj
- serial/VirtualSerial2/ComPort/VirtualSerial2um.vcxproj.Filters
- serial/VirtualSerial2/FakeModem/fakemodem2um.vcxproj
- serial/VirtualSerial2/FakeModem/fakemodem2um.vcxproj.Filters
- usb/usbsamp/sys/driver/usbsamp.vcxproj
- usb/usbsamp/sys/driver/usbsamp.vcxproj.Filters
Adding sha256 driver signing to additional driver samples
> Driver sample updates

- smartcrd/pscr/Pscr.vcxproj
Updating the smartcard pscr project to use SHA256.
> Updating the smartcard pscr project to use SHA256.

- general/tracing/tracedriver/tracedrv/tracedrv.vcxproj
- general/tracing/tracedriver/tracedrv/tracedrv.vcxproj.Filters
update driver signing to sha256
> update driver signing to sha256

- usb/UcmUcsiAcpiSample/UcmUcsiAcpiSample/Acpi.cpp
- usb/UcmUcsiAcpiSample/UcmUcsiAcpiSample/MemoryKm.cpp
Changing ExAllocatePoolWithTag to ExAllocatePool2
Disable the data role correction policy in UcmUcsiCx conditionally
Copying ACPI shared memory locally on UCSI notification
> Cumulative updates.

- biometrics/Package/package.VcxProj
- biometrics/driver/WudfBioUsbSample.vcxproj
- biometrics/driver/WudfBioUsbSample.vcxproj.Filters
> Changing driver signing to sha256.

- avstream/samplemft0/Mft0.cpp
* Check success of StringFromCLSID before printing string
* initialized wchar ptr to null
> Check success of StringFromCLSID before printing string (#1)

- network/wsk/echosrv/wsksmple.c
Requested to do so by CodeQL analysis
> Switch WSK Echosrv to ExAllocatePoolZero

- .github/scripts/Build-ChangedProjects.ps1
- Build-AllProjects.ps1
- Build-Project.ps1
- Build-ProjectSet.ps1
Escape emoji characters, add small validations to build scripts
> Miscellaneous build scripts fixes

- usb/usbview/xmlhelper.cpp
It's infinite loop when device desc isn't English
> [usb/usbview] fix infinite loop

- .github/workflows/CodeQL-Analysis
Creates CodeQL-Analysis workflow to run the latest CodeQL CLI and cpp rules against driver solutions which have changed. This is a CI mechanism to alert if there are CodeQL violations in projects which have been changed since the last commit.
> Creates CodeQL-Analysis Workflow

- pofx/PEP/acpi/acpispecific.c
https://github.com/microsoft/Windows-driver-samples/blob/main/pofx/PEP/acpi/acpispecific.c 
#PingMSFTDocs
> Typo "accpeted"→"accepted"

- .github/workflows/Code-Scanning.yml
- .github/workflows/ci-pr.yml
- .github/workflows/ci.yml
- Build-AllSamples.ps1
- Build-Sample.ps1
- Build-SampleSet.ps1
- Building-Locally.md
FI from main to develop. No functional change. This is simply an FI of https://github.com/microsoft/Windows-driver-samples/pull/863 .
> FI from main to develop.  No functional change.

- usb/UcmUcsiAcpiSample/UcmUcsiAcpiSample/Acpi.h
- usb/UcmUcsiAcpiSample/UcmUcsiAcpiSample/Fdo.cpp
- usb/UcmUcsiAcpiSample/UcmUcsiAcpiSample/Ppm.cpp
The issue is reported by `CodeQL` CLI version 2.11.5
Rules: `Windows-driver-developer-supplemental-tools/src/suites/ported_driver_ca_checks.qls`
VSO: 43490803
> [usb/UcmUcsiAcpiSample] Missing PAGED_CODE() macros

- usb/usbview/enum.c
> [usb/usbview] Enumerate HostController with multiple DeviceInterfaces

- gnss/gnssUmdf/gnssUmdf.vcxproj
Build looks good.
1>Building 'gnssUmdf' with toolset 'WindowsUserModeDriver10.0' and the 'Windows Driver' target platform.
1>Stamping C:\Users\chelee\source\repos\Windows-driver-samples\gnss\gnssUmdf\obj\x64\Debug\gnssUmdf.inf
1>Done Adding Additional Store
========== Rebuild All: 1 succeeded, 0 failed, 0 skipped ==========
> Windows Driver

- simbatt/func/wdf.c
Added missing PAGED_CODE() macro to wdf.c in simbatt driver
> Add missing PAGED_CODE() macro

- Build-Sample.ps1
- exclusions.csv
* Add more InfVerif warning exceptions to allow more samples to be built correctly.
* Treat warnings as errors to track them more efficiently.
* Remove exclusions related to InfVerif from some samples to monitor other issues.
> Add more InfVerif exceptions & clear exclusions

- setup/devcon/devcon.cpp
- setup/devcon/devcon.rc
Update devcon to RC file and input reading. Tested by building and running test commands that take some number of arguments and no arguments.
> Updates to DevCon RC file and input reading

- .github/scripts/Build-ChangedSamples.ps1
- Build-AllSamples.ps1
- Build-SampleSet.ps1
- exclusions.csv
* A Partial Manual Merge of develop to main branch specifically to add support for fine grained exclusions that was added to develop in https://github.com/microsoft/Windows-driver-samples/pull/1074 .
* Additionally, this PR includes a manually updated exclusion.csv file that is specific to the MAIN branch and incorporate necessary exceptions for current NI WDK and upcoming GE WDK.
(Example for x64 Debug)
Samples:              153
Configurations:       1 (Debug)
Platforms:            1 (x64)
Combinations:         153
Succeeded:            139
Excluded:             14
Unsupported:          0
Failed:               0
Samples:              153
Configurations:       2 (Debug Release)
Platforms:            2 (x64 arm64)
Combinations:         612
Succeeded:            317
Excluded:             59 …
> Partial Manual Merge of develop to main specifically to add support for fine grained exclusions

- Build-Sample.ps1
- Build-SampleSet.ps1
* A Partial Manual Merge of develop to main branch specifically to add /sw1402.  This is needed due to recent WDK GE changes.
> Partial Manual Merge of develop to main specifically to add /sw1402

- .github/CODEOWNERS
- exclusions.csv
- powerlimit/plclient/README.md
- powerlimit/plclient/plclient.asl
- powerlimit/plclient/plclient.c
- powerlimit/plclient/plclient.h
- powerlimit/plclient/plclient.inf
- powerlimit/plclient/plclient.rc
- powerlimit/plclient/plclient.sln
- powerlimit/plclient/plclient.vcxproj
- powerlimit/plclient/plclient.vcxproj.filters
- powerlimit/plclient/powerlimitclient_drvinterface.h
- powerlimit/plclient/wdf.c
- powerlimit/plpolicy/README.md
- powerlimit/plpolicy/plpolicy.c
- powerlimit/plpolicy/plpolicy.h
- powerlimit/plpolicy/plpolicy.inf
- powerlimit/plpolicy/plpolicy.rc
- powerlimit/plpolicy/plpolicy.sln
- powerlimit/plpolicy/plpolicy.vcxproj
- powerlimit/plpolicy/plpolicy.vcxproj.filters
- powerlimit/plpolicy/powerlimitpolicy_drvinterface.h
- powerlimit/plpolicy/sources
- powerlimit/plpolicy/wdf.c
This PR adds power limit policy and client driver as samples to use OS native power limit interfaces.
> Add power limit policy and client sample driver

- network/wwan/cxwmbclass/datapipe.cpp
- network/wwan/cxwmbclass/inc/util.h
- network/wwan/cxwmbclass/utils.cpp
> update with codel fix

- .github/workflows/Code-Scanning.yml
Update Code-Scanning.yml to version 1.2.0-beta of microsoft/windows-drivers pack. Also add config file for adding additional/experimental queries to code scanning.
The config file currently lives in the Windows Driver Developer Supplemental Tools repo, [here](https://github.com/microsoft/Windows-Driver-Developer-Supplemental-Tools/blob/development/config/codeql-config.yml)
The external location allows for adding/removing queries without needing to update the main Code-Scanning.yml file.
> Code scanning updates  (#1)
