serial/serial/pnp.c

fix the issue that user cannot open settings of serial port when using HyperTerminal under Windows XP.

Fix NULL-terminating device name when writing to DEVICEMAP/SERIALCOMM

---

usb/usbview/display.c

Display the connection info correctly even if the ConnectionInfoV2 is not
present.

Fix DisplayConnectionInfo

---

network/trans/msnmntr/sys/msnmntr.c

The exception occurs in MonitorCoStreamFlowDeletion, but the bug is in MonitorCoCreateFlowContext.
In 32-bit Windows, the high bit of kernel mode pointers is set, and the pointer value is 0x80000000 or above.  Casting 0x80000000 to a UINT64 yields 0xffffffff80000000 because of sign extension.  ULongLongToULongPtr converts 0xffffffff80000000 to 0xffffffff.  Boom.
Cast using an intermediate uintptr_t to avoid the sign extension in the first place.

Avoid 0x80000003 on 32-bit Windows in msnmntr.

---

setup/devcon/cmds.cpp
setup/devcon/devcon.cpp

Proposed changes because the output of the devcon for the russian version of windows was uninformative. For example, the output of "devcon.exe find usb\\*" command was as follows:
> USB\ROOT_HUB\4&1C7C1FAE&0                                   : ???????? USB-????????????
> USB\ROOT_HUB\4&3A448A3B&0                                   : ???????? USB-????????????
> USB\VID_09DA&PID_9090&MI_00\6&2FEDCB8B&0&0000               : USB-?????????? ?????
> 3 matching device(s) found.

added unicode support for devcon

---

audio/sysvad/SwapAPO/APO/SwapAPO.vcxproj

audio\sysvad\SwapAPO\APO\SwapAPO.vcxproj fails to compile.
With RS1 WDK, the warning is 4049; with RS2 WDK, the warning is 4217. Both uses VS 2015 compiler.

Ignore warning 4049 instead of 4127

---

setup/devcon/cmds.cpp
setup/devcon/msg.mc

Just like "findall" corresponds to "find" this new command acts like "remove" but it will also remove non-present devices.
So it is easy to remove all instances of an USB driver.

added a new devcon command "removeall"

---

general/ioctl/kmdf/exe/testapp.c

At installer.c `LoadWdfCoInstaller` function always get wrong coinstallerVersion 01011, even used `-v version` command line args.

Fix general/ioctl/kmdf/exe load wrong version of wdf controller dll.

---

tools/dv/samples/DV-FailDriver-WDM/driver/defect_toastmon.inf
tools/dv/samples/DV-FailDriver-WDM/driver/defect_toastmon.vcxproj
tools/dv/samples/DV-FailDriver-WDM/driver/defect_toastmon.vcxproj.Filters

The DV-FailDriver-WDM sample can't be properly deployed today, due to a combination of errors in the INF and project settings.
This PR cleans up the INF and updates the project settings to correctly create a catalog file and driver package.

Update DV-FailDriver-WDM sample to correctly create a driver package.

---

filesys/miniFilter/MetadataManager/support.c

With MetadataManager attached to a volume, open a DASD handle for GENERIC_READ, FILE_SHARE_READ.  MetadataManager should close its handle, but does not.  It is checking for DesiredAccess in addition to ShareMode, which is incorrect.  It should only check for ShareMode.

VSTS 15439953

---

filesys/cdfs/resrcsup.c

Hi,
This pull request fixes a bug that can be easily uncovered when using a CDFS checked build. CdAcquireForCache() sets the Top Level IRP before even attempting to lock the FCB resource. In case locking fails, the Top Level IRP is left set, and when a next call to CdAcquireForCache() is made, the assert is hit.
This commit fixes hit by setting the Top Level IRP after locking succeed (as done in FastFAT, for instance).
Cheers,
Pierre

Bugfix: don't set Top Level IRP if locking failed

---

general/SystemDma/wdm/exe/SystemDmaApp.vcxproj
general/cancel/exe/canclapp.vcxproj
general/event/exe/event.vcxproj
general/ioctl/wdm/exe/ioctlapp.vcxproj
general/pcidrv/test/myping.vcxproj
hid/firefly/app/flicker.vcxproj
hid/vhidmini2/app/testvhid.vcxproj
nfc/Simulator/Src/NfcDriverSim.vcxproj

Under x64 using VIsual Studio 15.5.4+, these projects now throw the warning LNK4281 "undesirable base address 0x400000 for x64 image; set base address above 4GB for best ASLR optimization".

Remove BaseAddress property from all projects to avoid warning LNK4281

---

filesys/miniFilter/simrep/simrep.c

This PR simply fixes some incorrect log lines in SimRepPreNetworkQueryOpen

Fix some log lines in SimRep

---

setup/devcon/devcon.sln
setup/devcon/devcon.vcxproj

While working on another project I realized I needed ARM64 Debug and Release configurations in the Devcon project. To consume it in automated builds, the change needs to be upstream.

Add ARM64 configurations to devcon solution

---

filesys/miniFilter/MetadataManager/support.c

For ReFS and NTFS the sample incorrectly considers the desired access, while for FAT it correctly only considers the share mode of the handle.  The way it is done for FAT is the way it should be done for all file systems.

Shouldn't consider desired access when checking for volume lock

---

filesys/fastfat/fsctrl.c
filesys/fastfat/volinfo.c

FAT Volume Label is stored in the root directory entry and therefore when
setting new Volume Label with leading 0xE5 byte it first needs to be
converted to 0x05 byte. This step is also required by Microsoft FAT
specification (fatgen103.doc) and also applied for all other files and
directories. But not for volume label yet. First byte 0xE5 in directory
entry means that entry is removed.
Similarly, when reading Volume Label from the root directory, leading byte
0x05 first needs to be converted to 0xE5 and then later processed. This is
reverse operation as described in previous paragraph.
FAT Volume Label is converted from Unicode to bytes according to OEM code
page. OEM code page is configured in Language for non-Unicode applications
settings in Country/Region settings.
When it is set to …

Fix changing and reading FAT labels with leading 0xE5 byte in fastfat.sys

---

tools/sdv/samples/SDV-FailDriver-WDM/driver/fail_driver1.c

Add a simple C28171 code analysis for drivers violation to the SDV-FailDriver-WDM sample, so that we can use it to validate CA for drivers is working correctly.

Add CA defect to SDV-FailDriver-WDM sample

---

network/wlan/WDI/PLATFORM/NDIS6/SDIO/N6SdioPlatformWindows.c
network/wlan/WDI/PLATFORM/NDIS6/SDIO/N6Sdio_main.c
network/wlan/WDI/PLATFORM/NDIS6/SDIO/sdio.vcxproj
network/wlan/WDI/PLATFORM/NDIS6/WDI_Cmds.c

- Use ExAllocatePool2 instead of ExAllocatePoolWithTag
- Fix build errors introduced in 2018

WDI sample: Use ExAllocatePool2 instead of ExAllocatePoolWithTag

---

print/OEM Printer Customization Plug-in Samples/README.md

I added statements about how to change Platform Toolset of the projects in Step 2-i.
When I used VS2017 and VS2019 to try to build the projects, Driver Files wasn't shown in the menu. 
So I think it is necessary to add these steps for people who download these good sample projects.
Could you help me check what I added is right or not?
Thank you
Best Regard,
Chao

Added configuration setting steps in Updated README.md 

---

hid/hclient/report.c

Data is pointer to array of HID_DATA structure.
Function advances pointer as it packs the report buffer.
At end of process in success condition, the function attempts to walk the array a second time and update the IsDataSet member for the HID_DATA elements that were packed.
What it's actually doing in the second pass is writing unexpected memory locations.
Fix is to store the head of the array and move back before walking again to set the bits.

fix bug in PackReport

---

network/trans/ddproxy/sys/DD_proxy.c

Modify the inbound NBL's UDP port # to that of the original outbound traffic, in order to meet the inbound filter conditions.
Through this change, calls to the inbound UDP filter's `classifyFn` can be observed.

ddproxy: Fix UDP inbound reinject scenario

---

network/ndis/ndisprot/6x/sys/60/ndisprot60.vcxproj
network/ndis/ndisprot/6x/sys/60/ndisprot60.vcxproj.Filters

built successfully using VS2019

Use SHA256 for ndisprot60's driver signing

---

network/trans/msnmntr/sys/msnmntr.c
network/trans/msnmntr/sys/notify.c

Updated sample to remove deprecated API usage (ExAllocatePoolWithTag to ExAllocatePoolZero)

msnmntr: Replace ExAllocatePoolWithTag with ExAllocatePoolZero

---

network/trans/inspect/inspect.sln
network/trans/inspect/sys/inspect.c
network/trans/inspect/sys/inspect.vcxproj
network/trans/inspect/sys/inspect.vcxproj.Filters

Changes a `NT_ASSERT` to match what the comment above is saying, the previous version caused a system crash if the packet was not inbound and had a auth decision made already. 
The comment
`         // Skip pended connections in the list, for which the auth decision is already taken.`
`         // They should not be for inbound connections.`
to my understanding means inbound connections should be ignored and ignore connections for which the auth decision was already made. The latter is checked by:
` if (packet->authConnectDecision == 0)` 
which keeps `found` equal to `FALSE` triggering the packet and list entry to be set to `NULL` here:
`if (!found)
{
listEntry = NULL;
packet = NULL;
}`
Change also updates the .sln and .vxproj  files so the sample compiles on VS2019 without any changes - …

Improvements to WFP Inspect Sample

---

serial/serial/wdfserial.vcxproj
usb/umdf2_fx2/driver/osrusbfx2um.vcxproj

Sets file digest algorith for wdfserial and usbfx2 drivers to SHA256
https://dev.azure.com/microsoft/OS/_workitems/edit/31022366
https://dev.azure.com/microsoft/OS/_workitems/edit/31022410
**How Tested:**
Compiling the two driver solutions shows they are correctly signed using SHA256

Use SHA256 for wdfserial and usbfx2 driver signing

---

network/ndis/filter/ndislwf.vcxproj
network/ndis/filter/ndislwf.vcxproj.Filters

Build successfully without file digest algorithm warning after the changes

Update ndis filter driver file digest algorithm to SHA256.

---

simbatt/func/simbatt.vcxproj
simbatt/func/simbatt.vcxproj.Filters

I have updated all four build flavors (Debug/Release and Win32/X64) to sign using sha256 instead of sha1 according to the instructions here: https://microsoft.visualstudio.com/OS/_queries/edit/31022338/?triage=true
Validated by building the drivers using all 4 combinations and verified the resulting catalogs are signed correctly using sha256

Change simbatt sample to sign with sha256 instead of sha1

---

tools/dv/samples/DV-FailDriver-WDM/driver/defect_toastmon.inf
tools/dv/samples/DV-FailDriver-WDM/driver/defect_toastmon.vcxproj

- Set `PnpLockdown=1` in the INF.
- Set SHA256 as the file signing algorithm in the project file.

DV-FailDriver-WDM: Add pnplockdown to INF and set file signing algorithm to sha256

---

audio/simpleaudiosample/Package/package.VcxProj
audio/simpleaudiosample/Source/Filters/Filters.vcxproj
audio/simpleaudiosample/Source/Inc/Inc.vcxproj
audio/simpleaudiosample/Source/Main/Main.vcxproj
audio/simpleaudiosample/Source/Utilities/Utilities.vcxproj
audio/sysvad/EndpointsCommon/EndpointsCommon.vcxproj
audio/sysvad/Package/package.VcxProj
audio/sysvad/TabletAudioSample/TabletAudioSample.vcxproj

Starting in Fe signtool generates a warning if no file digest algorithm is specified since it defaults to the insecure SHA1 algorithm. Windows-driver-samples admins are requiring sample owners to move to the more secure SHA256 algorithm so that no warning will come up.

Update SimpleAudioSample and Sysvad to use SHA256 signing.

---

general/echo/kmdf/driver/AutoSync/queue.c
general/echo/kmdf/driver/DriverSync/queue.c
general/ioctl/kmdf/sys/nonpnp.c
general/toaster/toastDrv/kmdf/bus/dynamic/buspdo.c
general/toaster/toastDrv/kmdf/func/featured/wmi.c
serial/serial/ioctl.c
serial/serial/openclos.c
usb/UcmCxUcsi/Acpi.cpp
usb/ufxclientsample/device.c
usb/usbsamp/sys/private.h
usb/usbsamp/sys/stream.c

`ExAllocatePoolWithTag` has being deprecated since Windows 2004/20H1 due to security issues (does not zero-initialize memory). 
[ExAllocatePool2](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nf-wdm-exallocatepool2) is now the preferred way to allocate pool memory.
Built all affected projects locally with latest public WDK (WDK for Windows 10, version 2004)

Buses samples should use ExAllocatePool2

---

print/XPSDrvSmpl/Package/package.VcxProj
print/autoconfig/AutoConfig.vcxproj
print/autoconfig/Package/package.VcxProj
print/v4PrintDriverSamples/v4PrintDriver-ConstraintScript/ConstraintScript.vcxproj
print/v4PrintDriverSamples/v4PrintDriver-USBMon-Bidi-Extension/USBMon-Bidi-Extension.vcxproj
print/v4PrintDriverSamples/v4PrintDriver-WSDMon-Bidi-Extension/WSDMon-Bidi-Extension.vcxproj

MSFT bug #32144470.
Validation:
Verified all modified projects still built in VS.

Add sha256 signing to applicable print WDK samples

---

tools/dv/samples/DV-FailDriver-WDM/defect_toastmon.c
tools/dv/samples/DV-FailDriver-WDM/wmi.c

Update DV-FailDriver-WDM sample to use ExAllocatePool2 per new guidance.

Remove deprecated API usage in DV-FailDriver-WDM sample.

---

bluetooth/bthecho/bthcli/sys/BthEchoSampleCli.vcxproj
bluetooth/bthecho/bthsrv/sys/BthEchoSampleSrv.vcxproj
bluetooth/bthecho/common/lib/bthecho.vcxproj
bluetooth/serialhcibus/WDK/SerialBusWdk.vcxproj

Updated the project build files to use sha256 for driver signing for the following bluetooth samples:
- bluetooth/bthecho/bthcli/sys/BthEchoSampleCli.vcxproj
- bluetooth/bthecho/bthsrv/sys/BthEchoSampleSrv.vcxproj
- bluetooth/bthecho/common/lib/bthecho.vcxproj
- bluetooth/serialhcibus/WDK/SerialBusWdk.vcxproj

Set driver signing algorithm to sha256 for some Bluetooth sample drivers.

---

usb/usbview/uvcview.c

Local variables may not be initialized prior to first access; initialize them at definition

Initialize local variables

---

avstream/avscamera/sys/AvsCamera.vcxproj

Fix bug where signing digest had incorrectly been stated as sha265 instead of sha256

Correct signing digest

---

network/trans/WFPSampler/sys/WFPSamplerCalloutDriver.vcxproj
network/trans/WFPSampler/syslib/WFPSampler.vcxproj
network/trans/ddproxy/sys/ddproxy.vcxproj
network/trans/inspect/sys/inspect.vcxproj
network/trans/msnmntr/sys/msnmntr.vcxproj
network/trans/stmedit/sys/stmedit.vcxproj

Updates vcxproj in the wfp sample drivers to include driver signing with SHA256. 
The following were not updated because they are not drivers: 
- \network\trans\msnmntr\exe\monitor.vcxproj
- \network\trans\WFPSampler\exe\WFPSampler.vcxproj
- \network\trans\WFPSampler\lib\WFPSampler.vcxproj
- \network\trans\WFPSampler\svc\WFPSamplerService.vcxproj

Update driver signing to SHA256

---

usb/UcmCxUcsi/Acpi.cpp

Changed Error message string to include the actual method name. Builds with Windows 11 EWDK with Visual Studio Build Tools 16.9.2

[UcmCxUcsi] Fix Acpi.cpp error msg string

---

bluetooth/serialhcibus/Io.h
bluetooth/serialhcibus/io.c

Due to the `ExAllocatePool` function being deprecated, we needed to update the API call to the ExAllocatePool2 function. The reason behind this change is that `ExAllocatePool` allocates memory that is uninitialized, users need to zero the memory before making it visible to users (Avoid leaking kernel-mode contents). In comparison, the memory that `ExAllocatePool2` allocates is already zero initialized; the security risk of disclosing information is not present with this function call.
The change was implemented by changing `ExAllocatePool` to a `ExAllocatePool2` function call. This was done with the help of the following APIs: [`ExAllocatePool`](`https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nf-wdm-exallocatepool`) and …

Changed ExAllocatePool to ExAllocatePool2 with tag

---

serial/VirtualSerial2/README.md

Update README.md for VirtualSerial2
due to the original README.md copy from VirtualSerial(UMDF1)

correct README.md of VirtualSerial2 driver

---

network/modem/fakemodem/driver.c

ref : MSFT 38345678: Update GitHub fakemodem sample to no longer use ExAllocatePool,

Update driver.c to no longer use ExAllocatePool

---

network/trans/ddproxy/sys/DD_drv.c
network/trans/ddproxy/sys/DD_proxy.c
network/trans/ddproxy/sys/ddproxy.inf
network/trans/ddproxy/sys/ddproxy.vcxproj
network/trans/ddproxy/sys/ddproxy.vcxproj.Filters
network/trans/inspect/sys/TL_drv.c
network/trans/inspect/sys/inspect.c
network/trans/inspect/sys/inspect.inf
network/trans/inspect/sys/utils.c
network/trans/stmedit/sys/InlineEdit.c
network/trans/stmedit/sys/LwQueue.c
network/trans/stmedit/sys/LwQueue.h
network/trans/stmedit/sys/OobEdit.c
network/trans/stmedit/sys/StreamEdit.c
network/trans/stmedit/sys/StreamEdit.h
network/trans/stmedit/sys/stmedit.inf
network/trans/stmedit/sys/stmedit.vcxproj
network/trans/stmedit/sys/stmedit.vcxproj.Filters

Per new security requirements the ExAllocatePoolWithTag are no longer secure using ExAllocatePoolZero instead of ExAllocatePool2 because these samples are downlevel drivers. Compiled with Visual Studio 2019. 
Also adds PnpLockdown = 1 to driver Inf files to resolve a compiler warning

[network\trans] ExAllocatePoolWithTag changing to ExAllocatePoolZero

---

network/trans/WFPSampler/syslib/HelperFunctions_Headers.cpp

Updating to repair a "Comparison with Wider Type" bug.

bug fix: updating UINT8 to UINT32 to correct wrong type comparison

---

storage/class/disk/src/disk.c
storage/class/disk/src/diskwmi.c
storage/class/disk/src/enum.c
storage/class/disk/src/geometry.c
storage/class/disk/src/pnp.c

Uses the newer zero-initializing malloc APIs.
Note changes between old POOL_TYPE enum:
https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/ne-wdm-_pool_type 
And new POOL_FLAGS enum:
https://docs.microsoft.com/en-us/windows-hardware/drivers/kernel/pool_flags 
Specifically, in _POOL_TYPE, non-paged pools are execuable by
default. Whereas in POOL_FLAGS, allocation of non-paged pools
must specifically request executability.
So,
- NonPagedPool -> POOL_FLAG_NON_PAGED_EXECUTE
- NonPagedPoolNx -> POOL_FLAG_NON_PAGED
- PagedPool -> POOL_FLAG_PAGED
See docs on updating old calls
https://docs.microsoft.com/en-us/windows-hardware/drivers/kernel/updating-deprecated-exallocatepool-calls 
Workitem: https://dev.azure.com/microsoft/OS/_workitems/edit/38345773/

Storage/Disk ExAllocatePool->ExAllocatePool2

---

hid/firefly/driver/vfeature.c

Replacing deprecated ExAllocatePoolWithTag to ExAllocatePool2. Builds with Windows 11 EWDK with Visual Studio Build Tools 16.9.2.

[hid\firefly] Replace ExAllocatePoolWithTag -> ExAllocatePool2

---

general/obcallback/driver/util.c

Replacing deprecated ExAllocatePoolWithTag to ExAllocatePool2. Builds with Windows 11 EWDK with Visual Studio Build Tools 17.1.5.

[general\obcallback] Replace ExAllocatePoolWithTag -> ExAllocatePool2

---

bluetooth/bthecho/bthcli/sys/client.c

**Why this change is needed?**
Due to the ExAllocatePool function being deprecated, we needed to update the API call to the ExAllocatePool2 function. The reason behind this change is that ExAllocatePool allocates memory that is uninitialized, users need to zero the memory before making it visible to users (Avoid leaking kernel-mode contents). In comparison, the memory that ExAllocatePool2 allocates is already zero initialized; the security risk of disclosing information is not present with this function call.
**How was this change implemented?**
The change was implemented by changing ExAllocatePoolWithTag to a ExAllocatePool2 function call. This was done with the help of the following APIs: ExAllocatePool and [ExAllocatePool2](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/w …

Removing instance of ExAllocatePoolWithTag

---

general/cancel/README.md
general/cancel/startio/cancel.c
general/cancel/startio/cancel.vcxproj
general/cancel/sys/cancel.c
general/cancel/sys/cancel.vcxproj
general/event/wdm/event.c
general/event/wdm/event.vcxproj

ExAllocatePoolWithQuotaTag has been deprecated in Windows 10 (v 2004),
this change replaces the calls to this functions.

Replace deprecated ExAllocatePoolWithQuotaTag call

---

general/toaster/toastDrv/kmdf/toastmon/toastmon.c
hid/firefly/driver/vfeature.c

Add handling case of non-successful return value of WdfIoTargetStart in toastmon.c. Builds with Windows 11 EWDK with Visual Studio Build Tools 16.9.2.

[general/toaster] Handle non successful return value of WdfIoTargetStart in toastmon.c

---

general/toaster/toastpkg/inf/autorun.inf
general/toaster/toastpkg/inf/toastpkg.inf
general/toaster/toastpkg/toastcd/autorun.inf
general/toaster/toastpkg/toastcd/toastpkg.inf
storage/class/disk/src/diskdev.inf
wia/microdrv/testmcro.inf

The last release of Windows that supported IA64 was many yeras ago.

Remove IA64 support from more samples

---

tools/dv/samples/DV-FailDriver-WDM/README.md
tools/dv/samples/DV-FailDriver-WDM/driver/defect_toastmon.inf

This change is being made to remove unsupported install for the `defect_toastmon` driver. To substitute this, documentation has been updated to encourage the use of `DevGen` as the preferred way to use the driver sample instead.

Update to DV-FailDriver-WDM

---

tools/dv/samples/DV-FailDriver-WDM/driver/defect_toastmon.inf

- removed the [ToastMonBuggy] section to eliminate emitted warning
Verified in local build that when change is made warning is resolved.

Fix unused warning

---

.github/workflows/Code-Scanning.yml

In accordance with this issue https://github.com/github/codeql-cli-binaries/issues/149 I have reconfigured to run code scanning on all PR's (to include text only changes) and adjusted the build command to build all solutions, not just the changed ones.

Re Configure Code-Scanning.yml

---

network/ndis/extension/samples/passthrough/mspassthroughext.inf

Fixed three INF Driver compatibility violations. Used the included install.cmd and uninstall.cmd to confirm that the install and uninstall completes, and the Driver Store is used.

mspassthroughext Driver compatibility violations

---

filesys/fastfat/lockctrl.c

The code grabs the FCB Shared, not Ex

Fix typo in comment

---

Build-SampleSet.ps1

A quick fix to a bug where errors were not shown even if builds would actually fail. This change also introduces a simple way to see details about the failed samples in the meantime while a better solution to make logs available is designed.

Fix logging when there are errors

---

.github/workflows/Code-Scanning.yml

Enable the CodeQL workflow to pull submodules similar to the regular workflow.
This also removes a "fetch-depth: 0" that as far as I understand documentation of "checkout" has been taking up unnecessary disk space.

Enable the CodeQL workflow to pull submodules similar to the regular workflow.

---

serial/serenum/enum.c
serial/serenum/log.c

Use ExAllocatePool2 instead of ExAllocatePoolWithTag

serenum sample: Use ExAllocatePool2 instead of ExAllocatePoolWithTag

---

exclusions.csv
network/trans/stmedit/stmedit.sln

When building the solution, Debug|x64 was treated as Debug|Win32 in the stmedit project. This has been fixed and the exclusion related to this error has been removed.

[network/trans/stmedit] Fix architecture in solution

---

.github/workflows/ci-pr.yml
.github/workflows/ci.yml
Build-SampleSet.ps1
Building-Locally.md

With this change, logs generated by the build actions will be archived for 90 days for users to download and review.
* Small change to the generated overview report name so it appears on top of a sorted file list.

Add logs as artifacts for actions

---

exclusions.csv
general/DCHU/osrfx2_DCHU_base/osrfx2_DCHU_base/osrfx2_DCHU_base.vcxproj
general/DCHU/osrfx2_DCHU_base/osrfx2_DCHU_filter/osrfx2_DCHU_filter.vcxproj
general/DCHU/osrfx2_DCHU_base/osrfx2_DCHU_testapp/osrusbfx2.vcxproj
general/DCHU/osrfx2_DCHU_base/osrfx2_DCHU_usersvc/osrfx2_DCHU_usersvc.vcxproj
general/DCHU/osrfx2_DCHU_extension_loose/osrfx2_DCHU_componentsoftware/osrfx2_DCHU_componentsoftware.vcxproj
general/DCHU/osrfx2_DCHU_extension_loose/osrfx2_DCHU_extension/osrfx2_DCHU_extension.vcxproj
general/DCHU/osrfx2_DCHU_extension_tight/osrfx2_DCHU_componentsoftware/osrfx2_DCHU_componentsoftware.vcxproj
general/DCHU/osrfx2_DCHU_extension_tight/osrfx2_DCHU_extension/osrfx2_DCHU_extension.vcxproj

* Set WindowsTargetPlatformVersion to target latest one instead of a fixed version
* Set PlatformToolset to target latest one instead of a fixed version
* Set FileDigestAlgorithm to clear errors caused by a digest algorithm not being specified
* Removed exception for general\dchu\osrfx2_dchu_base; sample now builds successfully. All other DCHU need additional work to build successfully,

[general/DCHU] Fix toolset, target version and signing errors

---

.github/scripts/Join-CsvReports.ps1
.github/workflows/ci-pr.yml
.github/workflows/ci.yml
.gitignore
Build-SampleSet.ps1

Build scripts provide a build report at the end of a run. These reports, one per combination of configuration and architecture, will now be submitted as a downloadable artifact. Moreover, at the end of a run, a global report condensing the other local reports will be generated as well by joining the other reports.
Testing was done in my local fork of the repository (results [here](https://github.com/NeoAdonis/Windows-driver-samples/actions)),

Generate and provide overview reports

---

thermal/simsensor/simsensor.c

The current implementation of simsensor doesn't match to the description of MSDN page. This change made the update to make them consistent.

Update simsensor driver on temperature check

---

setup/devcon/msg.mc

Add pnputil equivalents to devcon help text output. This output supports the ongoing efforts to migrate from devcon to pnputil.

Added pnputil equivalents to devcon help text output

---

Build-Sample.ps1
exclusions.csv

Temporary change to fix InfVerif build errors when using the build script with EEAP WDK and samples in development.

Add new flag and exclusion for new InfVerif changes

---

Build-Sample.ps1

Yesterday Friday's RS_SPARC build enables additional infverif checks.  Specifically warning 1402.  This warning is not cleaned up in samples yet, so I am excluding the flag.

Add infverif suppression of 1402

---

filesys/miniFilter/avscan/user/userscan.c

`dwErrCode` which is always 0.
We should use `GetLastError()` to get error code for `CloseHandle()`.

Fix error logging

---

video/KMDOD/memory.cxx

Re-doing this PR against the develop branch.

replace deprecated exallocatepool* APIs with their modern replacement

---

exclusions.csv
video/IndirectDisplay/IddSampleApp/IddSampleApp.vcxproj

Add explicit flag for arm64 for ehsc and remove incremental link as ehsc is not passsed for ARM64 VS and looks like ltcg is not supported as well.

Add explicit flag for arm64 for ehsc and remove incremental link

---

Build-Sample.ps1
Build-SampleSet.ps1

This PR enable retry logic to catch sporadic failures.
We /can/ do this now because samples in general are building extremely cleanly and Failures are mostly unexpected events.  (If we expect lots of failures, then retrying would take a lot of time)
We /should/ do this now because we have dramatically extended the number of combinations each build takes and the number of branches we test against.  What is perhaps only happening in 1 of 5000 combinations will statistically happens once if you build 125 drivers across 4 flavors across 10 builds.
How it works: 
Specifically, whenever a build failure occur for a given (Driver, Configuration, Platform) combination (say, video/indirectdisplay, Debug, arm64) the tool will re-run up to three times. If all three builds results in failure, then the …

Build System: Catch Sporadic Failures

---

TrEE/Miniport/SampleMiniport.c
TrEE/Miniport/TestService.c
TrEE/Miniport/TrEEMiniportSample.vcxproj
TrEE/TrEESample.sln
exclusions.csv

The TrEE sample is literally the last sample on our .\exclusion.csv list.  Let's get it to build!!
This fix does narrow fixes to achieve exactly that and at same time adds arm64 as a target OS.
More specifically:
* This PR removes TrEE from the .\exclusion.csv list.
* This PR adds arm64 target support to vcxproj and sln file.
* This PR avoid including non-existing header file and instead adds typedef directly (see beneath).
* This PR includes project header files with "..\inc\foo.h" rather than <foo.h>.  I am not quite sure what the best way to write this is.  But at least this works :-) .
* This PR fixes a requirement to not use ExAllocatePoolWithTag
How tested:
* Built for all four flavors in:
* WDK 22621
* EWDK.ni_release_svc_prod1.22621.2428
* EWDK.ge_release.26063.1
Note: There is no …

Fix TrEE Sample

---

network/ndis/mux/driver/60/novlan/mux.vcxproj
network/ndis/mux/driver/60/vlan/muxvlan.vcxproj
network/ndis/mux/mux.sln
network/ndis/mux/notifyob/mux.vcxproj
network/trans/WFPSampler/WFPSampler.sln
network/trans/WFPSampler/exe/WFPSampler.vcxproj
network/trans/WFPSampler/lib/WFPSampler.vcxproj
network/trans/WFPSampler/svc/WFPSamplerService.vcxproj
network/trans/WFPSampler/sys/WFPSamplerCalloutDriver.vcxproj
network/trans/WFPSampler/syslib/WFPSampler.vcxproj

The changes in this PR include adding new project configurations for ARM64 as well as properly setting up properties and additional dependencies for the ARM64 build.
Key changes:
* Added ARM64 as a new project configuration in both Debug and Release modes.
* Set up properties for the ARM64 platform, including target version, debug libraries, driver target platform, driver type, and platform toolset.
* Included additional dependencies for the ARM64 build.
* Added ARM64 to the list of platforms for which the `mux.dll` file is packaged.

Add ARM64 support on remaining network samples.

---

.github/workflows/Code-Scanning.yml
.github/workflows/ci-pr.yml
.github/workflows/ci.yml

actions/checkout to v4 and microsoft/setup-msbuild to v2

Update Code-Scanning.yml jobs to use Node.js 20

---

network/wlan/WDI/HEADER/PlatformDef.h
network/wlan/WDI/PLATFORM/NDIS6/Ndis6Common.c

The current implementation of the WDI driver example uses calls to deprecated NDIS functions: `NdisOpenFile`, `NdisMapFile`, `NdisUnmapFile`, `NdisCloseFile`. 
NDIS have deprecated the use of this functions and stick to only network-related operations which left this file operations not available for ARM64 architecture. Due to the current efforts to support ARM64, we need to refactor pieces of code within this driver to avoid the use of the deprecated NDIS calls such that we have a buildable driver for both x86_64 and ARM64. 
Refactored `PlatformReadFile`, `PlatformOpenFile`, `PlatformMapFile`, `PlatformUnMapFile`, `PlatformCloseFile` and `PlatformReadAndMapFile, to use the WDM calls for file operations and memory operations. This PR is the first step to enable the ARM64 support for this …

[WDI Sample] Refactoring Platform File IO ops to use WDM calls

---

network/trans/WFPSampler/svc/WFPSamplerService.vcxproj

Revert target platform for WFPSampler Service from Universal to Desktop to fix issue in WDK Preview.

[network/trans/WFPSampler] Fix driver target platform for service

---

input/kbfiltr/README.md

The current version of the `README.md` file for the keyboard filter driver sample erroneously includes what looks like boilerplate text in the callout at the bottom of the file. This text explains to the writer of the documentation what to include in the callout text, and should therefore have been removed when the actual content was added.
This change simply removes this change from the callout text.

Remove Boilerplate Text From Callout in Sample Keyboard Input Driver Doc

---

simbatt/func/miniclass.c

The `GetSimBattStateFromRegistry` function is currently using default settings if `GetSimBattStateFromRegistry` succeeds, whereas settings from registry are only applied if `GetSimBattStateFromRegistry` fails. This does not make sense to me.
Therefore proposing to remove the `!` negation from `if (!NT_SUCCESS(Status)) {` on the line after `Status = GetSimBattStateFromRegistry(Device, RegState);` so that default settings are loaded when registry read-back fails.

simbatt: Fix broken registry read-back

---

.github/scripts/Install-Vsix.ps1
.github/workflows/Code-Scanning.yml
.github/workflows/ci-pr.yml
.github/workflows/ci.yml
Build-SampleSet.ps1
Env-Vars.ps1

With the WDK now supporting Nuget packages for ease of install it is beneficial to have the CI pipeline also utilize this ability. This will allow easier and faster integration when new WDK versions are published without relying on the runner images to be updated.
- Adds Nuget package capability to the CI pipeline.
- Adds installation of WDK vsix directly into the CI pipeline.
- Updates environment variables for ease of incrementing component versions.
**BuildAll** (push and pull_request)
Without Vsix Install: ~08m 59s
With Vsix Install: ~38m 59s (optimized ~8m)
**CodeQL** (push and pull_request)
Without Vsix Install: ~1h 1m 43s
With Vsix Install: ~1h 34m 31s (optimized ~1h 16m 2s)
**Average** WDK Vsix Install Time
~21m (optimized ~15s)
**Average** WDK Nuget Restore
~1m 30s

CI Pipelines build with WDK Nuget Packages

---

.github/scripts/Install-Vsix.ps1
.github/workflows/Code-Scanning.yml
.github/workflows/ci-pr.yml
.github/workflows/ci.yml
Build-SampleSet.ps1
Building-Locally.md
Env-Vars.ps1

Additional improvements to the maintenance and documentation of the CI pipeline.
- Improved the vsix installer procedure by auto resolving the latest vsix, added additional logging, and removed sourcing of environment variables.
- Added NuGet package version and vsix version to the sample set build output.
- Updated the documentation for building locally by removing hardcoded version and improved the steps to install the WDK vsix extension from Visual Studio.

Improve version info, vsix installation, and update building locally documentation

---

sd/miniport/sdhc/sdhc.inx

Fix for sdhc sample using bootflags as a registry instead of the modern directive

Fix for sdhc sample using bootflags as a registry

---

audio/simpleaudiosample/Source/Filters/speakertoptable.h
audio/simpleaudiosample/Source/Main/common.cpp
audio/simpleaudiosample/Source/Main/minwavert.h
audio/simpleaudiosample/Source/Main/minwavertstream.h

Got some suggestions for fixes/changes to the sample from an external partner, this PR takes some of these small fixes and removes some dead code.

Small fixes to sample.

---

audio/sysvad/APO/AecApo/AecApo.vcxproj
audio/sysvad/APO/DelayAPO/DelayAPO.vcxproj
audio/sysvad/APO/KWSApo/KWSApo.vcxproj
audio/sysvad/APO/SwapAPO/SwapAPO.vcxproj
audio/sysvad/EndpointsCommon/EndpointsCommon.vcxproj
audio/sysvad/EndpointsCommon/NewDelete.cpp
audio/sysvad/EndpointsCommon/NewDelete.h
audio/sysvad/KeywordDetectorAdapter/KeywordDetectorContosoAdapter.vcxproj
audio/sysvad/TabletAudioSample/TabletAudioSample.vcxproj

Update `audio/sysvad` project to use C++17 standard as required by the latest version of WIL. This also required adding a new `delete` operator override new to C++17.

[audio/sysvad] Use C++17

---

avstream/sampledevicemft/SampleSocDeviceMFTutils.cpp
avstream/sampledevicemft/dllmain.cpp
avstream/sampledevicemft/multipinmft.vcxproj
avstream/sampledevicemft/multipinmftutils.cpp

* Update `avstream/sampledevicemft` project to use C++17 standard as required by the latest version of WIL.
* Fix incomplete lambda error in `avstream/sampledevicemft/dllmain.cpp` by adding `noexcept` specifier to the lambda function in `wil::SetResultLoggingCallback`.
* Fix type ambiguity error in `avstream/sampledevicemft/multipinmftutils.cpp`.

[avstream/sampledevicemft] Use C++17

---

Build-Sample.ps1
Build-SampleSet.ps1

This pull request includes a few improvements and fixes to the `Build-Sample.ps1` and `Build-SampleSet.ps1` scripts to enhance readability, maintainability, and functionality.
- `Build-Sample.ps1`: Changed the loop condition to use `-lt 3` (less than) to understand better the upper limit of build attempts.
- Added handling for binary log file creation to help diagnose issues when a build fails.
- Replaced shortcuts with long expressions for better readability and to remove warnings.
- Fix issue where building samples using the EWDK was not supported by the build scripts.
- Other minor whitespace fixes.

Miscellaneous improvements to build scripts

---

serial/VirtualSerial2/queue.c

Warning C26837
https://learn.microsoft.com/en-us/cpp/code-quality/c26837?view=msvc-170

[serial/VirtualSerial2] Use helper function ReadNoFence to read lineControlRegister to avoid C26837

---

general/ioctl/kmdf/exe/nonpnpapp.vcxproj
network/ndis/ndisprot_kmdf/notifyob/ProtNotify.vcxproj
network/wlan/WDI/PLATFORM/NDIS6/SDIO/n6c_sdio.inc.props

The latest WDK only supports Windows 10+, and WDF version 15+ is inbox on Win10. This PR updates the samples to use WDF v15+ to align with the latest WDK version.
Test: 
1 - Install EWDK
2 - Remove KMDF < 1.15 and UMDF 2.0 headers/libs from EWDK
3 - Build-AllSamples.ps1 finishes without problem

Update samples to use WDF v15+

---

Build-SampleSet.ps1

Build-sample set was printing an error message when trying to find the WDK version while using the EWDK.

Fix the wdk version in EWDK

---

serial/serial/ioctl.c

Currently the Serial sample driver sets wakeSettings.UserControlOfWakeSettings to an incompatible enum type. The value was updated to be WakeDoNotAllowUserControl so that the driver can build correctly instead.

Updated Sample Driver Enum
